version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull xd009642/tarpaulin
          command: docker pull xd009642/tarpaulin:latest
      - run:
          name: Generate report
          command: >
            docker run --security-opt seccomp=unconfined -e CODECOV_TOKEN=${CODECOV_TOKEN}
            -v $PWD:/volume xd009642/tarpaulin cargo tarpaulin -v --ciserver circle-ci
            --out Xml --all-features
      - run:
          name: Upload
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
